######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 23 21:23:21 2008
######################################################################

TEMPLATE = app
DESTDIR = ..\..\..\bin
TARGET = sjc_testmain
DEPENDPATH += .
INCLUDEPATH += ..\sjc_testutility
DEFINES += SJCTESTMAINDLL
LIBS += $${DESTDIR}\sjc_testutility.lib
QT += testlib

# Input
HEADERS += 
SOURCES += testmain.cpp
