######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 23 21:23:21 2008
######################################################################

TEMPLATE = lib
DESTDIR = ..\..\bin
TARGET = sjc_utility
DEPENDPATH += .
INCLUDEPATH += .
DEFINES += SJCUTILITYDLL

# Input
HEADERS += sphere3d.h vector3d.h dllspecutility.h line3d.h matrix.h plane3d.h
SOURCES += sphere3d.cpp vector3d.cpp line3d.cpp matrix.cpp plane3d.cpp
