######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 23 21:23:21 2008
######################################################################

TEMPLATE = lib
DESTDIR = ..\..\..\bin
TARGET = sjc_testutility
DEPENDPATH += .
INCLUDEPATH += ..\..\sjc_utility
DEFINES += SJCTESTUTILITYDLL
LIBS += $${DESTDIR}\sjc_utility.lib
QT += testlib

# Input
HEADERS += testvector3d.h dllspec.h testline3d.h
SOURCES += testvector3d.cpp testline3d.cpp
