######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 23 21:23:21 2008
######################################################################

TEMPLATE = lib
DESTDIR = ..\..\..\bin
TARGET = sjc_testpole
DEPENDPATH += .
INCLUDEPATH += .
DEFINES += SJCTESTPOLEDLL

# Input
HEADERS += testpole.h dllspec.h
SOURCES += testpole.cpp
